[project]
name = "malarz"
version = "0.1.0"
description = "Bergen Community College STEM Research Center Machine Learning with Python Workshop."
readme = "README.md"
authors = [
    { name = "ghost", email = "belikesnab@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "torch>=2.8.0",
]

[project.scripts]
malarz = "malarz:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
